### ISSUE TITLE
Compléter la documentation

### ISSUE THREAD

**Issue by Pavell94000** [PremierLangage/PLaTon-doc#5]
Il manque plein de choses (mais je sais pas quoi)

**Comment by Pavell94000** [comment]
C'est @nimdanor qui a balancé

**Comment by nborie** [comment]
Tant d'énervement.....

**Comment by nborie** [comment]
Je vais fermer le ticket avec la réponse du CRI :

C'est ouvert depuis tellement longtemps que ça a bien dû être fait....

Trêve de plaisanterie, faut ré ouvrir le cas échéant avec une truc précis seulement pas un ticket bomb comme ça...
